---
title: "About"
date: 2019-08-27T00:00:26+08:00
---

= About

Hey! 
This is Terminal Plus-Minus, a https://gohugo.io/[Hugo] theme 
based from https://github.com/panr/hugo-theme-terminal[original Terminal] 
originally developed by https://github.com/panr/[panr].

It is basically a recreation of the original theme with the following 
new and improved features:

* Focused support for https://asciidoctor.org/[Asciidoctor]-based content. 
* Removal of https://nodejs.org/[NodeJS] dependencies through the use of 
https://gohugo.io/hugo-pipes/bundling/[Hugo asset bundling]. 
* Easier configuration for site appearance 
* Using as a single homepage theme 
* Using as a blogging theme 
* Even using as both single homepage with a blog 
* Static site engine widget (not recommended for large sites)
* Support for RSS, Atom, and JSON feeds 
* MathJax support 
* Theme toggle (AKA dark mode)
* Site breadcrumbs 
* Customizable social links 

If you're interested in trying this theme, you can visit the 
https://github.com/foo-dogsquared/hugo-theme-terminal-plus-minus[GitHub repo] for 
more information.
Feel free to file an issue for requesting features or bug reports and create 
a pull request.

You could also see the 
https://gitlab.com/foo-dogsquared/hugo-theme-terminal-plus-minus[GitLab mirror] if 
you're mainly using GitLab.

This theme is created and currently maintained by 
https://foo-dogsquared.github.io/[@foo-dogsquared]. 
He also uses this theme for https://foo-dogsquared.github.io/blog/[his blog] 
and https://foo-dogsquared.github.io/[web portfolio], obviously. 
I guess you could say he's dogfooding. 
